#
#  node.yml
#  Sportiv
#
#  Created by Yefta Sutanto on 01/03/21.
#

name: CI (Build & Test)

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build_and_test:
    name: Build & Test for mergeability
    runs-on: ubuntu-latest
    steps:
      - name: Are we PR-ing against dev?
        if: github.base_ref == 'development'
        run: |
          echo "NODE_ENV=development" >> $GITHUB_ENV
      - name: Are we PR-ing against main?
        if: github.base_ref == 'main'
        run: |
          echo "GITHUB_REF_SLUG=latest" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Build
        run: npm run generate
